services:
  - type: web
    name: scrapsandscholars-client
    rootDir: scrapsandscholars.client
    buildCommand: npm install && npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: development